version: '3.8'

services:
  app:
    build: 
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://niasur:q3X7URkZN2UUHfPZ@cicdunitesting.yrnl0.mongodb.net/
    command: npm run dev
    ports:
      - "3000:3000"
      - "9229:9229"  # For debugging
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db

volumes:
  mongodb_dev_data: