version: '3.8'

services:
  app:
    build: .
    environment:
      - NODE_ENV=test
      - MONGODB_URI=mongodb+srv://niasur:q3X7URkZN2UUHfPZ@cicdunitesting.yrnl0.mongodb.net/
    depends_on:
      - mongodb
    command: npm test
    networks:
      - test-network

  mongodb:
    image: mongo:5.0
    networks:
      - test-network

networks:
  test-network:
    driver: bridge